version: '3'
services:
  backend:
    build: ./tiny-url-backend
    container_name: tiny-url-backend
    ports:
      - '4000:4000'
    environment:
      - AWS_REGION=us-east-1
      - AWS_SDK_LOAD_CONFIG=1  # Cargar la configuración de AWS
