version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo-container
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: tiny-url-backend
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/tinyurl

volumes:
  mongo-data:
